repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=10000']
    -   id: check-ast
    -   id: detect-private-key
    -   id: fix-encoding-pragma
    -   id: check-symlinks
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
    -   id: requirements-txt-fixer
