# Config file for tractography parameters.
l_max: 8
batch_size: 10

# Seed point creation
seed:
    peaks: 2
    min_odf_amplitude: 0.1
    min_peak_separation_arc_len: 0.34906585
    # Possible values: symmetric362, symmetric642, symmetric724, repulsion724,
    # repulsion100, repulsion200
    dipy_sphere: 'repulsion200'

# Streamline tracking parameters
tracking:
    step_size_mm: 0.4
    alpha_exponential_moving_avg: 0.85

# Peak finding parameters.
peak_finding:
    lr: 0.1
    momentum: 0.5
    max_epochs: 250
    tol_arc_len: 0.00017453292519943296

# Stopping criteria
stopping:
    min_streamline_len: 10
    max_streamline_len: 300
    min_gfa: 0.5
    min_odf_amplitude: 0.1
    max_tangent_angle_diff: 0.4363323129985824
