name: pitn
channels:
  - mrtrix3
  - simpleitk
  - nodefaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - absl-py==1.2.0
  - aiohttp==3.8.1
  - aiosignal==1.2.0
  - alsa-lib==1.2.8
  - anyio==3.6.2
  - aom==3.4.0
  - appdirs==1.4.4
  - apscheduler==3.6.3
  - argon2-cffi==21.3.0
  - argon2-cffi-bindings==21.2.0
  - asn1crypto==1.5.1
  - asttokens==2.0.8
  - async-timeout==4.0.2
  - atk-1.0==2.36.0
  - attr==2.5.1
  - attrs==22.1.0
  - backcall==0.2.0
  - basemap==1.3.4
  - basemap-data==1.3.2
  - beautifulsoup4==4.11.1
  - black
  - black-jupyter==22.6.0
  - blas==1.0
  - blas-devel==3.9.0
  - bleach==5.0.1
  - blinker==1.4
  - blosc==1.21.1
  - boltons==21.0.0
  - bottleneck==1.3.5
  - brotli==1.0.9
  - brotli-bin==1.0.9
  - brotlipy==0.7.0
  - brunsli==0.1
  - bzip2==1.0.8
  - c-ares==1.18.1
  - c-blosc2==2.2.0
  - ca-certificates
  - cachecontrol==0.12.11
  - cached-property==1.5.2
  - cachetools==4.2.2
  - cachy==0.3.0
  - cairo==1.16.0
  - certifi
  - cffi==1.15.1
  - cfgv==3.3.1
  - cfitsio==4.1.0
  - charls==2.3.4
  - charset-normalizer==2.1.0
  - cleo==0.8.1
  - click==8.1.3
  - click-default-group==1.2.2
  - clikit==0.6.2
  - cloudpickle==2.1.0
  - cmake==3.24.2
  - comm==0.1.2
  - conda==22.11.1
  - conda-package-handling==1.8.1
  - conda-package-streaming==0.7.0
  - crashtest==0.3.1
  - cryptography==39.0.1
  - cuda==11.7.1
  - cuda-cccl==11.7.91
  - cuda-command-line-tools==11.7.1
  - cuda-compiler==11.7.1
  - cuda-cudart==11.7.99
  - cuda-cudart-dev==11.7.99
  - cuda-cuobjdump==11.7.91
  - cuda-cupti==11.7.101
  - cuda-cuxxfilt==11.7.91
  - cuda-demo-suite==12.0.76
  - cuda-documentation==12.0.76
  - cuda-driver-dev==11.7.99
  - cuda-gdb==11.8.86
  - cuda-libraries==11.7.1
  - cuda-libraries-dev==11.7.1
  - cuda-memcheck==11.8.86
  - cuda-nsight==11.8.86
  - cuda-nsight-compute==11.8.0
  - cuda-nvcc==11.7.99
  - cuda-nvdisasm==11.8.86
  - cuda-nvml-dev==11.7.91
  - cuda-nvprof==11.8.87
  - cuda-nvprune==11.7.91
  - cuda-nvrtc==11.7.99
  - cuda-nvrtc-dev==11.7.99
  - cuda-nvtx==11.7.91
  - cuda-nvvp==11.8.87
  - cuda-runtime==11.7.1
  - cuda-samples==11.6.101
  - cuda-sanitizer-api==11.8.86
  - cuda-toolkit==11.7.1
  - cuda-tools==11.7.1
  - cuda-visual-tools==11.7.1
  - cudatoolkit[version='<=11.7']
  - cudnn==8.4.1.50
  - curl==7.87.0
  - cvxpy==1.3.1
  - cvxpy-base==1.3.1
  - cycler==0.11.0
  - cython==0.29.32
  - cytoolz==0.12.0
  - dask-core==2022.8.0
  - dav1d==1.0.0
  - debugpy==1.6.3
  - decorator==5.1.1
  - defusedxml==0.7.1
  - deprecated==1.2.13
  - dill==0.3.6
  - dipy==1.5.0
  - distlib==0.3.5
  - distro==1.6.0
  - docker-py==5.0.3
  - docker-pycreds==0.4.0
  - double-conversion==3.2.0
  - eigen==3.4.0
  - einops==0.6.0
  - ensureconda==1.4.3
  - entrypoints==0.4
  - exceptiongroup==1.1.1
  - executing==0.10.0
  - expat==2.5.0
  - ffmpeg==4.4.2
  - fftw==3.3.10
  - filelock==3.8.0
  - flake8
  - flit-core==3.8.0
  - font-ttf-dejavu-sans-mono==2.37
  - font-ttf-inconsolata==3.000
  - font-ttf-source-code-pro==2.038
  - font-ttf-ubuntu==0.83
  - fontconfig==2.14.2
  - fonts-conda-ecosystem==1
  - fonttools==4.35.0
  - freetype==2.12.1
  - fribidi==1.0.10
  - frozenlist==1.3.1
  - fslpy==3.10.0
  - fsspec==2022.8.2
  - fury==0.8.0
  - future==0.18.2
  - g-ir-build-tools==1.72.0
  - g-ir-host-tools==1.72.0
  - gcc==12.1.0
  - gcc_impl_linux-64==12.1.0
  - gdk-pixbuf==2.42.8
  - gds-tools==1.4.0.31
  - geos==3.11.0
  - gettext==0.21.1
  - giflib==5.2.1
  - gl2ps==1.4.2
  - glew==2.1.0
  - glib==2.74.1
  - glib-tools==2.74.1
  - gmp==6.2.1
  - gnutls==3.7.7
  - gobject-introspection==1.72.0
  - google-auth==2.10.0
  - google-auth-oauthlib==0.4.6
  - gputil==1.4.0
  - graphviz==5.0.1
  - greenlet==1.1.2
  - grpc-cpp==1.51.1
  - grpcio==1.51.1
  - gst-plugins-base==1.21.3
  - gstreamer==1.21.3
  - gstreamer-orc==0.4.33
  - gtk2==2.24.33
  - gts==0.7.6
  - h5py==3.7.0
  - harfbuzz==5.1.0
  - hdf4==4.2.15
  - hdf5==1.12.1
  - html5lib==1.1
  - humanize==4.3.0
  - icecream==2.1.3
  - icu==70.1
  - identify==2.5.3
  - idna==3.3
  - imagecodecs==2022.8.8
  - imageio==2.21.1
  - importlib-metadata==4.11.4
  - importlib_metadata==4.11.4
  - importlib_resources==5.9.0
  - iniconfig==2.0.0
  - ipdb==0.13.9
  - ipykernel
  - ipympl==0.9.1
  - ipython
  - ipython_genutils==0.2.0
  - ipywidgets==7.7.1
  - isort==5.10.1
  - jack==1.9.22
  - jedi==0.18.1
  - jeepney==0.8.0
  - jinja2==3.1.2
  - joblib==1.1.0
  - jpeg==9e
  - jsoncpp==1.9.5
  - jsonpickle==2.2.0
  - jsonschema==4.9.1
  - jupyter_client==7.3.4
  - jupyter_core==4.11.1
  - jupyter_events==0.5.0
  - jupyter_server==1.23.4
  - jupyter_server_terminals==0.4.3
  - jupyterlab_pygments==0.2.2
  - jupyterlab_widgets==1.1.1
  - jupytext==1.14.0
  - jxrlib==1.1
  - kernel-headers_linux-64==2.6.32
  - keyring==23.8.2
  - keyutils==1.6.1
  - kiwisolver==1.4.4
  - knockknock==0.1.8.1
  - krb5==1.20.1
  - lame==3.100
  - lcms2==2.12
  - lerc==4.0.0
  - libabseil==20230125.0
  - libaec==1.0.6
  - libarchive==3.6.2
  - libavif==0.10.1
  - libblas==3.9.0
  - libbrotlicommon==1.0.9
  - libbrotlidec==1.0.9
  - libbrotlienc==1.0.9
  - libcap==2.66
  - libcblas==3.9.0
  - libclang==15.0.7
  - libclang13==15.0.7
  - libcublas==11.11.3.6
  - libcublas-dev==11.11.3.6
  - libcufft==10.9.0.58
  - libcufft-dev==10.9.0.58
  - libcufile==1.4.0.31
  - libcufile-dev==1.4.0.31
  - libcups==2.3.3
  - libcurand==10.3.0.86
  - libcurand-dev==10.3.0.86
  - libcurl==7.87.0
  - libcusolver==11.4.1.48
  - libcusolver-dev==11.4.1.48
  - libcusparse==11.7.5.86
  - libcusparse-dev==11.7.5.86
  - libdb==6.2.32
  - libdeflate==1.13
  - libdrm==2.4.112
  - libev==4.33
  - libevent==2.1.10
  - libffi==3.4.2
  - libflac==1.4.2
  - libgcc==7.2.0
  - libgcc-devel_linux-64==12.1.0
  - libgcc-ng==12.1.0
  - libgcrypt==1.10.1
  - libgd==2.3.3
  - libgfortran-ng==12.1.0
  - libgfortran5==12.1.0
  - libgirepository==1.72.0
  - libglib==2.74.1
  - libglu==9.0.0
  - libgomp==12.1.0
  - libgpg-error==1.46
  - libgrpc==1.51.1
  - libiconv==1.17
  - libidn2==2.3.3
  - libitk==5.2.1
  - libitk-devel==5.2.1
  - liblapack==3.9.0
  - liblapacke==3.9.0
  - libllvm10==10.0.1
  - libllvm11==11.1.0
  - libllvm14==14.0.6
  - libllvm15==15.0.7
  - libnetcdf==4.8.1
  - libnghttp2==1.51.0
  - libnpp==11.8.0.86
  - libnpp-dev==11.8.0.86
  - libnsl==2.0.0
  - libnvjpeg==11.9.0.86
  - libnvjpeg-dev==11.9.0.86
  - libopenblas==0.3.21
  - libopus==1.3.1
  - libpciaccess==0.16
  - libpng==1.6.39
  - libpq==15.1
  - libprotobuf==3.21.12
  - libqdldl==0.1.5
  - librsvg==2.54.4
  - libsanitizer==12.1.0
  - libsndfile==1.2.0
  - libsodium==1.0.18
  - libsolv==0.7.22
  - libsqlite==3.40.0
  - libssh2==1.10.0
  - libstdcxx-ng==12.1.0
  - libsystemd0==252
  - libtasn1==4.18.0
  - libtheora==1.1.1
  - libtiff==4.4.0
  - libtool==2.4.7
  - libudev1==252
  - libunistring==0.9.10
  - libuuid==2.32.1
  - libuv==1.44.2
  - libva==2.15.0
  - libvorbis==1.3.7
  - libvpx==1.11.0
  - libwebp==1.2.4
  - libwebp-base==1.2.4
  - libxcb==1.13
  - libxkbcommon==1.0.3
  - libxml2==2.10.3
  - libxslt==1.1.35
  - libzip==1.9.2
  - libzlib==1.2.13
  - libzopfli==1.0.3
  - lightning-utilities==0.6.0.post0
  - llvm-openmp==14.0.4
  - llvmlite==0.39.1
  - locket==1.0.0
  - lockfile==0.12.2
  - loguru==0.6.0
  - lxml==4.9.1
  - lz4-c==1.9.3
  - lzo==2.10
  - magma==2.5.4
  - make==4.3
  - markdown==3.4.1
  - markdown-it-py==2.1.0
  - matplotlib==3.5.2
  - matplotlib-base==3.5.2
  - matplotlib-inline==0.1.3
  - matplotx==0.3.7
  - matrix_client==0.4.0
  - mccabe==0.7.0
  - mdit-py-plugins==0.3.1
  - mdurl==0.1.0
  - mistune==0.8.4
  - mock==4.0.3
  - monai
  - more-itertools==8.14.0
  - mpg123==1.31.2
  - mrtrix3==3.0.4
  - msgpack-python==1.0.4
  - multidict==6.0.2
  - multiprocess==0.70.14
  - munkres==1.1.4
  - mypy_extensions==0.4.3
  - mysql-common==8.0.32
  - mysql-libs==8.0.32
  - natsort==8.1.0
  - nb_conda_kernels
  - nbclassic==0.4.8
  - nbclient==0.6.6
  - nbconvert==6.5.3
  - nbconvert-core==6.5.3
  - nbconvert-pandoc==6.5.3
  - nbformat==5.4.0
  - nbstripout==0.6.0
  - nccl==2.14.3.1
  - ncurses==6.3
  - nest-asyncio==1.5.5
  - nettle==3.8.1
  - networkx==2.8.5
  - ninja==1.11.0
  - nodeenv==1.7.0
  - notebook==6.4.12
  - notebook-shim==0.2.2
  - nsight-compute==2022.3.0.22
  - nspr==4.35
  - nss==3.82
  - numba==0.56.4
  - numpy==1.23.4
  - oauthlib==3.2.0
  - openblas==0.3.21
  - openh264==2.3.0
  - openjpeg==2.5.0
  - openssl
  - opt_einsum==3.3.0
  - osqp==0.6.2.post0
  - p11-kit==0.24.1
  - pandas==1.5.2
  - pandoc==2.19
  - pandocfilters==1.5.0
  - pango==1.50.9
  - parso==0.8.3
  - partd==1.3.0
  - pastel==0.2.1
  - pathos==0.3.0
  - pathspec==0.9.0
  - patsy==0.5.2
  - pcre==8.45
  - pcre2==10.40
  - pexpect==4.8.0
  - pickleshare==0.7.5
  - pillow==9.2.0
  - pip
  - pixman==0.40.0
  - pkg-config==0.29.2
  - pkginfo==1.8.3
  - pkgutil-resolve-name==1.3.10
  - platformdirs==2.5.2
  - pluggy==1.0.0
  - ply==3.11
  - portalocker==2.5.1
  - portaudio==19.6.0
  - pox==0.3.2
  - ppft==1.7.6.6
  - pprintpp==0.4.0
  - pre-commit==2.20.0
  - pretty_errors
  - proj==9.0.1
  - prometheus_client==0.14.1
  - prompt-toolkit==3.0.30
  - psutil==5.9.1
  - ptyprocess==0.7.0
  - pugixml==1.11.4
  - pulseaudio==16.1
  - pure_eval==0.2.2
  - pybind11-abi==4
  - pycodestyle==2.9.1
  - pycosat==0.6.3
  - pycparser==2.21
  - pydantic==1.9.2
  - pydeprecate==0.3.2
  - pydicom==2.3.0
  - pyflakes==2.5.0
  - pygments==2.13.0
  - pyjwt==2.4.0
  - pylev==1.4.0
  - pyopenssl==23.0.0
  - pyparsing==3.0.9
  - pyproj==3.3.1
  - pyqt==5.15.7
  - pyqt5-sip==12.11.0
  - pyrsistent==0.18.1
  - pyshp==2.1.3
  - pysocks==1.7.1
  - pytables==3.7.0
  - pytest==7.3.1
  - python==3.10.9
  - python-box==6.0.2
  - python-dateutil==2.8.2
  - python-fastjsonschema==2.16.1
  - python-json-logger==2.0.4
  - python-levenshtein==0.12.2
  - python-telegram-bot==13.13
  - python_abi==3.10
  - pytorch==1.13.1
  - pytorch-cuda==11.7
  - pytransform3d==3.1.0
  - pytz==2022.2.1
  - pyu2f==0.1.5
  - pywavelets==1.3.0
  - pyzmq==23.2.1
  - qdldl-python==0.1.5.post2
  - qt==5.15.6
  - qt-main==5.15.6
  - qt-webengine==5.15.4
  - qtwebkit==5.212
  - re2==2023.02.02
  - readline==8.1.2
  - reproc==14.2.4
  - reproc-cpp==14.2.4
  - requests==2.28.1
  - requests-oauthlib==1.3.1
  - requests-toolbelt==0.9.1
  - rhash==1.4.3
  - ruamel.yaml==0.17.21
  - scikit-build==0.16.2
  - scikit-image==0.19.3
  - scikit-learn==1.1.3
  - scipy==1.9.3
  - scs==3.2.3
  - seaborn
  - secretstorage==3.3.3
  - send2trash==1.8.0
  - setuptools==59.5.0
  - shellingham==1.5.0
  - simpleitk==2.2.0
  - sip==6.6.2
  - six==1.15.0
  - sleef==3.5.1
  - snappy==1.1.9
  - sniffio==1.3.0
  - soupsieve==2.3.2.post1
  - sqlite==3.39.2
  - stack_data==0.4.0
  - statsmodels==0.13.2
  - svt-av1==1.2.1
  - sysroot_linux-64==2.12
  - tabulate==0.9.0
  - tbb==2021.5.0
  - tbb-devel==2021.5.0
  - tensorboard==2.10.1
  - tensorboard-data-server==0.6.1
  - tensorboard-plugin-wit==1.8.1
  - terminado==0.15.0
  - thefuzz==0.19.0
  - threadpoolctl==3.1.0
  - tifffile==2022.8.12
  - tikzplotlib==0.10.1
  - timm==0.4.12
  - tinycss2==1.1.1
  - tk==8.6.12
  - tokenize-rt==4.2.1
  - toml==0.10.2
  - tomli==2.0.1
  - tomlkit==0.11.4
  - toolz==0.12.0
  - torchinfo==1.7.1
  - torchio==0.18.84
  - torchmetrics==0.10.0
  - torchvision==0.14.1
  - tornado==6.2
  - tqdm==4.64.0
  - traitlets==5.3.0
  - transforms3d==0.4.1
  - twilio==7.12.1
  - typeguard==4.0.0
  - typing==3.10.0.0
  - typing-extensions==4.6.2
  - typing_extensions==4.6.2
  - tzdata==2022c
  - tzlocal==2.1
  - ubelt==1.2.1
  - ujson==5.4.0
  - ukkonen==1.0.1
  - unicodedata2==14.0.0
  - urllib3==1.26.11
  - utfcpp==3.2.2
  - virtualenv==20.16.3
  - vtk==9.1.0
  - watermark==2.3.1
  - wcwidth==0.2.5
  - webcolors==1.12
  - webencodings==0.5.1
  - websocket-client==1.3.3
  - werkzeug==2.2.2
  - wheel==0.37.1
  - widgetsnbextension==3.6.1
  - wrapt==1.14.1
  - x264==1!164.3095
  - x265==3.5
  - xcb-util==0.4.0
  - xcb-util-image==0.4.0
  - xcb-util-keysyms==0.4.0
  - xcb-util-renderutil==0.3.9
  - xcb-util-wm==0.4.1
  - xorg-fixesproto==5.0
  - xorg-kbproto==1.0.7
  - xorg-libice==1.0.10
  - xorg-libsm==1.2.3
  - xorg-libx11==1.7.2
  - xorg-libxext==1.3.4
  - xorg-libxfixes==5.0.3
  - xorg-libxrender==0.9.10
  - xorg-libxt==1.2.1
  - xorg-renderproto==0.11.1
  - xorg-xextproto==7.3.0
  - xorg-xproto==7.0.31
  - xz==5.2.6
  - yagmail==0.15.283
  - yaml==0.2.5
  - yaml-cpp==0.7.0
  - yarl==1.7.2
  - zeromq==4.3.4
  - zfp==1.0.0
  - zipp==3.8.1
  - zlib==1.2.13
  - zlib-ng==2.0.6
  - zstandard==0.19.0
  - zstd==1.5.2
  - lightning
