name: pitn
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - cudatoolkit=11.6
  - numpy
  - pytorch
  - torchvision
  - torchdata
  - pytorch-lightning
  - torchio
  - monai
  - einops
  - scipy
  - scikit-image
  - scikit-learn
  - dipy
  - mrtrix3
  - nibabel
  - pandas
  - matplotlib
  - tensorboard
  - seaborn
  - ipympl
  - redun
  - natsort
  - toolz
  - boltons
  - ubelt
  - more-itertools
  - thefuzz
  - appdirs
  - python-box
  - pillow
  - cloudpickle
  - jsonpickle
  - dill
  - loguru
  - icecream
  - pprintpp
  - watermark
  - torchinfo
  - ipdb
  - ipython
  - pip
  - mamba
  - conda-lock
  - black
  - flake8
  - pretty_errors
  - tqdm
  - pre-commit
  - ipykernel
  - nb_conda_kernels
  - nbconvert
  - nbformat
  - nbstripout
  - timm
  - pytransform3d
  - ipywidgets
  - fslpy
  - matplotx
  - tikzplotlib
  - knockknock
  - ca-certificates
  - certifi
  - openssl
  - cython
  - packaging[version='>=20.4,<21.0']
  - docker-py
  - isort
  - black-jupyter
