experiment_name: "fenri_test_ismrm_sim"
baseline_lr_spacing_scale: 2.222222
baseline_snr: 30
train_val_test_split_file: "data_splits/ISMRM-HCP-sim_train-val-test_split_01.csv"
train:
    patch_size: [36, 36, 36]
    batch_size: 6
    samples_per_subj_per_epoch: 300
    max_epochs: 50
    dwi_recon_epoch_proportion: 0.0
    patch_sampling:
        rng: "default"
    patch_tf:
        downsample_factor_range: [2.222222, 2.777777]
        noise_snr_range: [25, 35]
        prefilter_sigma_scale_coeff: 2.0
        rng: "default"
    optim:
        encoder:
            lr: 5.0E-4
        decoder:
            lr: 5.0E-4
    dataloader:
        num_workers: 16
        persistent_workers: True
        prefetch_factor: 3
preproc_loaded:
    S0_noise_b0_quantile: 0.99
    patch_sampling_w_erosion: 20
val:
    rng_seed: 3967417599011123030
    vol_tf:
        downsample_factor_range: [2.222222, 2.222222]
        noise_snr_range: [30, 30]
        prefilter_sigma_scale_coeff: 2.0
        manual_crop_lr_sides: [[1, 1], [1, 1], [1, 1]]
# Network/model parameters.
encoder:
    in_channels: 102
    interior_channels: 80
    out_channels: 96
    n_res_units: 3
    n_dense_units: 3
    activate_fn: "relu"
    input_coord_channels: True
    post_batch_norm: True
decoder:
    context_v_features: 96
    out_features: 45
    m_encode_num_freqs: 36
    sigma_encode_scale: 3.0
    n_internal_features: 256
    n_internal_layers: 3
test:
    rng_seed: 3967417599011123030
    vol_tf:
        downsample_factor_range: [2.222222, 2.222222]
        noise_snr_range: [30, 30]
        prefilter_sigma_scale_coeff: 2.0
        manual_crop_lr_sides: [[1, 1], [1, 1], [1, 1]]
